title = "Redis Custom Synchronization"
description = "对某些 key 做同步拉取"

# 同步时间间隔，可以看作是休眠时间 单位：毫秒
interval    = 100
# 将 TTL信息带过来
enablettl   = true
keysfile = "./keysfile"
patterns = [
    # 一行一个通配符 "WechatService.AccToken*",
]

[source]
host = ""
port = 6379
db   = 1
auth = ""

[destination]
host = ""
port = 6379
db   = 5
auth = ""
